version: '3.4'

services:
  catalogdb:
    image: postgres
    environment:
        POSTGRES_PASSWORD: postgres

  basketdb:
    image: postgres
    environment:
        POSTGRES_PASSWORD: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  

